version: '3'

services:
  apache:
    image: httpd:2.4.48
    ports:
      - '80:80'
    volumes:
      - './htdocs:/usr/local/apache2/htdocs'
    restart: always

  mysql:
    image: mysql:8.0.26
    ports:
      - '3306:3306'
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=Admin.123!
    restart: always

  php:
    image: php:8.0.11-apache
    volumes:
      - './htdocs:/var/www/html'
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=Admin.123!
    restart: always

